In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

# Introduction
### Background
When Andrew Bogut went on a podcast in 2022, he stated "One thing that was crazy about that run was the shit that I used to get away with screening, man it was all time" and "Then I get traded to Dallas to set those same screens and I'd get 3 fouls in the first quarter, It was just crazy with the stuff I used to get away with there". Bogut was an integral part of the beginning of the Warriors dynasty that started in 2015 with their first championship run. The Warriors dynasty won one out of their four championships with Bogut on the team. 

The Warriors under coach Steve Kerr have had their fair share of criticism of their play style, which involves a lot of screens to get their star players and shooters, Steph Curry and Klay Thompson (later Kevin Durant). An example of this occurs in the 2023 playoffs, during the second round against the Lakers. There were multiple instances of the players on the Warriors setting screens that seemed to be bending the rules, with a lot of slight movements and leaning, which is not really clearly marked as illegal and is up to the referees' discretion. This, combined with Bogut's quote, made me think, will the data show this as well?

### Question
Is Andrew Bogut's claim supported by the data? If so, is it limited to players like him or would it be applicable to all players who had a part of the Warriors dynasty?

# Exploratory Data Analysis

In [2]:
per_36 = pd.read_csv('NBA_Data/Per 36 Minutes.csv')
per_36.head()

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
0,30458,2023,5025,A.J. Green,NaN,SG,23.0,1,NBA,MIL,...,1.000,0.6,4.1,4.7,2.3,0.6,0.0,0.9,3.2,16.1
1,30459,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,TOT,...,0.250,2.0,5.0,7.0,0.7,0.7,0.0,1.0,3.7,18.7
2,30460,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,MIN,...,NaN,0.0,18.0,18.0,0.0,0.0,0.0,0.0,18.0,36.0
3,30461,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,DAL,...,0.250,2.0,4.8,6.8,0.7,0.7,0.0,1.0,3.4,18.3
4,30462,2023,4219,Aaron Gordon,NaN,PF,27.0,9,NBA,DEN,...,0.608,2.9,4.9,7.8,3.6,0.9,0.9,1.7,2.3,19.4

Since we want to focus on Warriors players during the beginning of the Warriors dynasty, lets get the roster.

In [3]:
warriors = per_36[per_36['tm'] == 'GSW']
warriors15 = warriors[warriors['season'] == 2015]
warriors15_players = warriors15['player']
warriors15_players

5423          Andre Iguodala
5430            Andrew Bogut
5473            Brandon Rush
5529               David Lee
5554          Draymond Green
5584            Festus Ezeli
5618         Harrison Barnes
5663    James Michael McAdoo
5738          Justin Holiday
5764           Klay Thompson
5787         Leandro Barbosa
5815       Marreese Speights
5867           Ognjen KuzmiÄ‡
5945        Shaun Livingston
5959           Stephen Curry
Name: player, dtype: object

We can see the number of personal fouls each member of that roster commited per 36 minutes that season.

In [4]:
warriors15[['player', 'pf_per_36_min']]

                    player  pf_per_36_min
5423        Andre Iguodala            1.7
5430          Andrew Bogut            4.3
5473          Brandon Rush            3.6
5529             David Lee            3.3
5554        Draymond Green            3.7
5584          Festus Ezeli            5.5
5618       Harrison Barnes            2.3
5663  James Michael McAdoo            5.5
5738        Justin Holiday            3.0
5764         Klay Thompson            1.8
5787       Leandro Barbosa            3.2
5815     Marreese Speights            5.6
5867         Ognjen KuzmiÄ‡            6.5
5945      Shaun Livingston            2.7
5959         Stephen Curry            2.2

Now we want to get the numbers for their whole careers, but we can see the data isn't clean because there was a David Lee in the 1970's in the ABA, as well as a David Lee in the 2000's and 2010's. Well we can remedy that by removing all ABA players.

In [5]:
per_36[per_36['player'].isin(warriors15_players)]

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
20,30478,2023,3500,Andre Iguodala,NaN,SF,39.0,19,NBA,GSW,...,0.667,1.0,4.5,5.4,6.1,1.3,1.0,2.9,3.5,5.4
164,30622,2023,4085,Draymond Green,NaN,PF,32.0,11,NBA,GSW,...,0.713,1.0,7.2,8.2,7.8,1.2,0.9,3.2,3.6,9.7
220,30678,2023,4089,Harrison Barnes,NaN,PF,30.0,11,NBA,SAC,...,0.847,1.2,3.8,4.9,1.7,0.8,0.1,1.2,1.4,16.6
351,30809,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,TOT,...,0.625,0.3,2.5,2.8,2.1,1.0,1.0,1.1,3.5,10.5
352,30810,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,ATL,...,NaN,0.2,1.8,2.0,2.2,0.4,0.9,1.1,3.2,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11572,19651,2005,3462,Leandro Barbosa,NaN,PG,22.0,2,NBA,PHO,...,0.797,1.1,3.2,4.3,4.2,1.0,0.2,2.9,4.2,14.6
11738,19817,2005,3560,Shaun Livingston,NaN,PG,19.0,1,NBA,LAC,...,0.746,1.0,3.0,3.9,6.7,1.4,0.5,3.3,3.6,9.8
12141,19050,2004,3462,Leandro Barbosa,NaN,PG,21.0,1,NBA,PHO,...,0.770,0.6,2.4,3.0,4.0,2.2,0.2,2.9,4.4,13.2
27325,3582,1969,941,David Lee,1942.0,SF,26.0,2,ABA,NOB,...,NaN,6.8,0.0,6.8,0.0,NaN,NaN,4.5,0.0,4.5
27731,3202,1968,941,David Lee,1942.0,SF,25.0,1,ABA,OAK,...,0.857,NaN,NaN,8.8,1.0,NaN,NaN,2.0,4.0,17.8

In [6]:
nba = per_36[per_36['lg'] == 'NBA']
nba.head()

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
0,30458,2023,5025,A.J. Green,NaN,SG,23.0,1,NBA,MIL,...,1.000,0.6,4.1,4.7,2.3,0.6,0.0,0.9,3.2,16.1
1,30459,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,TOT,...,0.250,2.0,5.0,7.0,0.7,0.7,0.0,1.0,3.7,18.7
2,30460,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,MIN,...,NaN,0.0,18.0,18.0,0.0,0.0,0.0,0.0,18.0,36.0
3,30461,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,DAL,...,0.250,2.0,4.8,6.8,0.7,0.7,0.0,1.0,3.4,18.3
4,30462,2023,4219,Aaron Gordon,NaN,PF,27.0,9,NBA,DEN,...,0.608,2.9,4.9,7.8,3.6,0.9,0.9,1.7,2.3,19.4

That's better. No more outlier that we aren't looking for!

In [7]:
war_car = nba[nba['player'].isin(warriors15_players)]
war_car

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
20,30478,2023,3500,Andre Iguodala,NaN,SF,39.0,19,NBA,GSW,...,0.667,1.0,4.5,5.4,6.1,1.3,1.0,2.9,3.5,5.4
164,30622,2023,4085,Draymond Green,NaN,PF,32.0,11,NBA,GSW,...,0.713,1.0,7.2,8.2,7.8,1.2,0.9,3.2,3.6,9.7
220,30678,2023,4089,Harrison Barnes,NaN,PF,30.0,11,NBA,SAC,...,0.847,1.2,3.8,4.9,1.7,0.8,0.1,1.2,1.4,16.6
351,30809,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,TOT,...,0.625,0.3,2.5,2.8,2.1,1.0,1.0,1.1,3.5,10.5
352,30810,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,ATL,...,NaN,0.2,1.8,2.0,2.2,0.4,0.9,1.1,3.2,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11158,20385,2006,3560,Shaun Livingston,NaN,PG,20.0,2,NBA,LAC,...,0.688,1.0,3.4,4.3,6.4,1.1,0.8,2.6,3.8,8.3
11258,19337,2005,3500,Andre Iguodala,NaN,SG,21.0,1,NBA,PHI,...,0.743,1.2,5.0,6.2,3.3,1.8,0.6,1.9,2.7,9.9
11572,19651,2005,3462,Leandro Barbosa,NaN,PG,22.0,2,NBA,PHO,...,0.797,1.1,3.2,4.3,4.2,1.0,0.2,2.9,4.2,14.6
11738,19817,2005,3560,Shaun Livingston,NaN,PG,19.0,1,NBA,LAC,...,0.746,1.0,3.0,3.9,6.7,1.4,0.5,3.3,3.6,9.8
12141,19050,2004,3462,Leandro Barbosa,NaN,PG,21.0,1,NBA,PHO,...,0.770,0.6,2.4,3.0,4.0,2.2,0.2,2.9,4.4,13.2

Some players appear to have their team as TOT but there is no NBA team like that. Let's see how many instances of that there are.

In [8]:
war_car[war_car['tm'] == 'TOT']

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
351,30809,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,TOT,...,0.625,0.3,2.5,2.8,2.1,1.0,1.0,1.1,3.5,10.5
1105,30073,2022,4102,Justin Holiday,NaN,SF-SG,32.0,9,NBA,TOT,...,0.806,0.5,2.8,3.3,2.2,1.0,0.6,1.2,2.7,13.1
3085,27821,2019,4089,Harrison Barnes,NaN,PF-SF,26.0,7,NBA,TOT,...,0.824,0.8,4.3,5.1,1.6,0.7,0.2,1.4,1.7,18.0
3218,27954,2019,4102,Justin Holiday,NaN,SG,29.0,6,NBA,TOT,...,0.896,0.6,3.8,4.5,2.0,1.7,0.5,1.4,2.3,11.8
4240,26345,2017,3573,Andrew Bogut,NaN,C,32.0,12,NBA,TOT,...,0.273,3.5,10.0,13.5,3.0,0.8,1.5,2.7,5.3,4.9
4943,25875,2016,3590,David Lee,1983.0,PF,32.0,11,NBA,TOT,...,0.763,4.0,8.1,12.2,3.3,0.9,1.1,2.6,4.5,17.0
5121,26053,2016,4102,Justin Holiday,NaN,SG,26.0,3,NBA,TOT,...,0.730,0.6,3.6,4.2,2.6,1.5,0.9,1.8,2.8,11.1
7052,24309,2013,3837,Marreese Speights,NaN,C,25.0,5,NBA,TOT,...,0.771,4.0,6.6,10.7,1.3,0.7,1.5,2.2,4.8,18.2
7150,24407,2013,3560,Shaun Livingston,NaN,PG,27.0,8,NBA,TOT,...,0.867,0.8,3.1,3.9,5.3,1.2,0.8,1.9,3.1,10.3
7570,23703,2012,3462,Leandro Barbosa,NaN,SG,29.0,9,NBA,TOT,...,0.815,0.9,2.5,3.3,2.5,1.5,0.2,2.4,3.5,18.4
8905,22659,2010,3560,Shaun Livingston,NaN,PG,24.0,5,NBA,TOT,...,0.875,0.7,2.8,3.5,5.9,0.8,0.5,2.6,2.8,11.3
9484,22078,2009,3560,Shaun Livingston,NaN,PG,23.0,4,NBA,TOT,...,0.900,0.5,3.9,4.4,3.1,1.1,0.3,1.4,1.9,11.1

Let's pick out Shaun Livingston since he has TOT appear multiple times. As we can see below, TOT appears when a player switches teams mid season. That might mess with the data a bit so let's drop that.

In [9]:
war_car[war_car['player'] == 'Shaun Livingston']

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
3430,28166,2019,3560,Shaun Livingston,NaN,PG,33.0,14,NBA,GSW,...,0.784,1.6,2.8,4.4,4.2,1.2,1.0,1.4,2.8,9.6
4123,27487,2018,3560,Shaun Livingston,NaN,PG,32.0,13,NBA,GSW,...,0.820,1.0,3.2,4.2,4.5,1.1,0.7,1.8,3.7,12.6
4725,26830,2017,3560,Shaun Livingston,NaN,PG,31.0,12,NBA,GSW,...,0.700,0.7,3.3,4.0,3.7,1.0,0.5,1.7,3.2,10.4
5316,26248,2016,3560,Shaun Livingston,NaN,PG,30.0,11,NBA,GSW,...,0.860,1.0,3.0,4.0,5.6,1.4,0.6,1.8,3.3,11.6
5945,25648,2015,3560,Shaun Livingston,NaN,PG,29.0,10,NBA,GSW,...,0.714,1.1,3.4,4.5,6.4,1.2,0.5,2.5,2.7,11.3
6581,25022,2014,3560,Shaun Livingston,NaN,PG,28.0,9,NBA,BRK,...,0.827,1.2,3.3,4.5,4.5,1.7,0.6,1.9,3.1,11.5
7150,24407,2013,3560,Shaun Livingston,NaN,PG,27.0,8,NBA,TOT,...,0.867,0.8,3.1,3.9,5.3,1.2,0.8,1.9,3.1,10.3
7151,24408,2013,3560,Shaun Livingston,NaN,PG,27.0,8,NBA,WAS,...,1.000,0.2,3.9,4.2,4.3,1.2,0.2,1.9,2.5,7.1
7152,24409,2013,3560,Shaun Livingston,NaN,PG,27.0,8,NBA,CLE,...,0.843,0.9,2.9,3.8,5.6,1.2,0.9,1.9,3.3,11.2
7710,23843,2012,3560,Shaun Livingston,NaN,SG,26.0,7,NBA,MIL,...,0.785,1.3,2.8,4.1,4.0,0.9,0.7,2.2,2.6,10.5
8324,23281,2011,3560,Shaun Livingston,NaN,PG,25.0,6,NBA,CHA,...,0.864,0.8,3.4,4.3,4.7,1.3,0.8,2.5,3.1,13.7
8905,22659,2010,3560,Shaun Livingston,NaN,PG,24.0,5,NBA,TOT,...,0.875,0.7,2.8,3.5,5.9,0.8,0.5,2.6,2.8,11.3
8906,22660,2010,3560,Shaun Livingston,NaN,PG,24.0,5,NBA,OKC,...,NaN,1.1,4.4,5.5,3.9,1.4,0.6,2.2,2.5,2.8
8907,22661,2010,3560,Shaun Livingston,NaN,PG,24.0,5,NBA,WAS,...,0.875,0.6,2.5,3.1,6.3,0.6,0.5,2.7,2.8,13.0
9484,22078,2009,3560,Shaun Livingston,NaN,PG,23.0,4,NBA,TOT,...,0.900,0.5,3.9,4.4,3.1,1.1,0.3,1.4,1.9,11.1
9485,22079,2009,3560,Shaun Livingston,NaN,PG,23.0,4,NBA,MIA,...,0.750,0.0,1.8,1.8,3.5,1.8,0.0,2.6,3.5,7.9
9486,22080,2009,3560,Shaun Livingston,NaN,PG,23.0,4,NBA,OKC,...,1.000,0.6,4.4,4.9,3.0,0.9,0.4,1.1,1.5,11.7
10606,20912,2007,3560,Shaun Livingston,NaN,PG,21.0,3,NBA,LAC,...,0.707,1.3,2.9,4.1,6.1,1.3,0.6,2.4,3.0,11.2
11158,20385,2006,3560,Shaun Livingston,NaN,PG,20.0,2,NBA,LAC,...,0.688,1.0,3.4,4.3,6.4,1.1,0.8,2.6,3.8,8.3
11738,19817,2005,3560,Shaun Livingston,NaN,PG,19.0,1,NBA,LAC,...,0.746,1.0,3.0,3.9,6.7,1.4,0.5,3.3,3.6,9.8

In [10]:
tots = war_car[war_car['tm'] == 'TOT'].index
no_tot = war_car.drop(tots)
no_tot

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
20,30478,2023,3500,Andre Iguodala,NaN,SF,39.0,19,NBA,GSW,...,0.667,1.0,4.5,5.4,6.1,1.3,1.0,2.9,3.5,5.4
164,30622,2023,4085,Draymond Green,NaN,PF,32.0,11,NBA,GSW,...,0.713,1.0,7.2,8.2,7.8,1.2,0.9,3.2,3.6,9.7
220,30678,2023,4089,Harrison Barnes,NaN,PF,30.0,11,NBA,SAC,...,0.847,1.2,3.8,4.9,1.7,0.8,0.1,1.2,1.4,16.6
352,30810,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,ATL,...,NaN,0.2,1.8,2.0,2.2,0.4,0.9,1.1,3.2,11.0
353,30811,2023,4102,Justin Holiday,NaN,SG,33.0,10,NBA,DAL,...,0.625,0.4,3.5,3.9,2.0,1.7,1.1,1.2,3.8,9.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11158,20385,2006,3560,Shaun Livingston,NaN,PG,20.0,2,NBA,LAC,...,0.688,1.0,3.4,4.3,6.4,1.1,0.8,2.6,3.8,8.3
11258,19337,2005,3500,Andre Iguodala,NaN,SG,21.0,1,NBA,PHI,...,0.743,1.2,5.0,6.2,3.3,1.8,0.6,1.9,2.7,9.9
11572,19651,2005,3462,Leandro Barbosa,NaN,PG,22.0,2,NBA,PHO,...,0.797,1.1,3.2,4.3,4.2,1.0,0.2,2.9,4.2,14.6
11738,19817,2005,3560,Shaun Livingston,NaN,PG,19.0,1,NBA,LAC,...,0.746,1.0,3.0,3.9,6.7,1.4,0.5,3.3,3.6,9.8
12141,19050,2004,3462,Leandro Barbosa,NaN,PG,21.0,1,NBA,PHO,...,0.770,0.6,2.4,3.0,4.0,2.2,0.2,2.9,4.4,13.2

In [11]:
roster_fouls = no_tot[['season', 'player_id', 'player', 'pos', 'tm', 'pf_per_36_min']]
roster_fouls

       season  player_id            player pos   tm  pf_per_36_min
20       2023       3500    Andre Iguodala  SF  GSW            3.5
164      2023       4085    Draymond Green  PF  GSW            3.6
220      2023       4089   Harrison Barnes  PF  SAC            1.4
352      2023       4102    Justin Holiday  SG  ATL            3.2
353      2023       4102    Justin Holiday  SG  DAL            3.8
...       ...        ...               ...  ..  ...            ...
11158    2006       3560  Shaun Livingston  PG  LAC            3.8
11258    2005       3500    Andre Iguodala  SG  PHI            2.7
11572    2005       3462   Leandro Barbosa  PG  PHO            4.2
11738    2005       3560  Shaun Livingston  PG  LAC            3.6
12141    2004       3462   Leandro Barbosa  PG  PHO            4.4

[169 rows x 6 columns]

In [12]:
roster_fouls.groupby(['season', 'player_id'])['pf_per_36_min'].mean()

season  player_id
2004    3462         4.4
2005    3462         4.2
        3500         2.7
        3560         3.6
2006    3462         3.3
                    ...
2023    3903         2.2
        4036         2.1
        4085         3.6
        4089         1.4
        4102         3.5
Name: pf_per_36_min, Length: 157, dtype: float64

Just seeing these numbers is not really conclusive proof of anything though. We should break it down player by player and see if there was a shift in fouls before and after their stints with the team. We can start off with the player who started this conversation, Andrew Bogut.

In [13]:
roster_fouls[roster_fouls['player'] == 'Andrew Bogut']

       season  player_id        player pos   tm  pf_per_36_min
2869     2019       3573  Andrew Bogut   C  GSW            5.9
3577     2018       3573  Andrew Bogut   C  LAL            6.7
4241     2017       3573  Andrew Bogut   C  DAL            5.2
4242     2017       3573  Andrew Bogut   C  CLE           72.0
4842     2016       3573  Andrew Bogut   C  GSW            5.5
5430     2015       3573  Andrew Bogut   C  GSW            4.3
6075     2014       3573  Andrew Bogut   C  GSW            4.3
6675     2013       3573  Andrew Bogut   C  GSW            3.9
7244     2012       3573  Andrew Bogut   C  MIL            3.6
7808     2011       3573  Andrew Bogut   C  MIL            3.4
8435     2010       3573  Andrew Bogut   C  MIL            3.6
9015     2009       3573  Andrew Bogut   C  MIL            4.2
9590     2008       3573  Andrew Bogut   C  MIL            3.4
10189    2007       3573  Andrew Bogut   C  MIL            3.4
10701    2006       3573  Andrew Bogut  PF  MIL            4.0

72 fouls in 36 minutes does not seem to add up in my eyes so I'd like to check how many games he played in Cleveland versus Dallas, which was the team he mentioned in the quote.

In [14]:
totals = pd.read_csv('NBA_Data/Player Totals.csv')
totals.head()

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,30458,2023,5025,A.J. Green,NaN,SG,23.0,1,NBA,MIL,...,1.000,6.0,39.0,45.0,22,6.0,0.0,9.0,31,154
1,30459,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,TOT,...,0.250,6.0,15.0,21.0,2,2.0,0.0,3.0,11,56
2,30460,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,MIN,...,NaN,0.0,1.0,1.0,0,0.0,0.0,0.0,1,2
3,30461,2023,5026,A.J. Lawson,NaN,SG,22.0,1,NBA,DAL,...,0.250,6.0,14.0,20.0,2,2.0,0.0,3.0,10,54
4,30462,2023,4219,Aaron Gordon,NaN,PF,27.0,9,NBA,DEN,...,0.608,164.0,282.0,446.0,203,54.0,51.0,98.0,129,1109

In [15]:
bogut_total = totals[totals['player'] == 'Andrew Bogut']
bogut_total[['season', 'tm', 'g', 'mp']]

       season   tm   g      mp
2869     2019  GSW  11   134.0
3577     2018  LAL  24   216.0
4240     2017  TOT  27   583.0
4241     2017  DAL  26   582.0
4242     2017  CLE   1     1.0
4842     2016  GSW  70  1451.0
5430     2015  GSW  67  1583.0
6075     2014  GSW  67  1769.0
6675     2013  GSW  32   786.0
7244     2012  MIL  12   364.0
7808     2011  MIL  65  2297.0
8435     2010  MIL  69  2229.0
9015     2009  MIL  36  1124.0
9590     2008  MIL  78  2720.0
10189    2007  MIL  66  2258.0
10701    2006  MIL  82  2348.0

From the above queries, we can determine that the 72 fouls per 36 minutes played is indeed just an outlier and it is due to the fact that he only played in one game in Cleveland. We can also see that in that one game that he did play, he only had 1 minute played, meaning he received 2 fouls in that 1 minute, thus skewing the fouls per 36 minute statistic. However, we do see that he did, on average, commit more fouls on other teams after he had left Golden State. For comparison, we should look at other big men on the team who also left Golden State.

In [16]:
roster_fouls[roster_fouls['player'] == 'David Lee']

       season  player_id     player pos   tm  pf_per_36_min
4347     2017       3590  David Lee  PF  SAS            3.0
4944     2016       3590  David Lee  PF  BOS            3.9
4945     2016       3590  David Lee  PF  DAL            5.2
5529     2015       3590  David Lee  PF  GSW            3.3
6181     2014       3590  David Lee  PF  GSW            3.2
6775     2013       3590  David Lee  PF  GSW            3.0
7350     2012       3590  David Lee  PF  GSW            3.0
7927     2011       3590  David Lee  PF  GSW            2.9
8543     2010       3590  David Lee   C  NYK            3.1
9130     2009       3590  David Lee   C  NYK            3.3
9707     2008       3590  David Lee  PF  NYK            3.2
10278    2007       3590  David Lee  PF  NYK            3.2
10807    2006       3590  David Lee  SF  NYK            4.0

In [17]:
roster_fouls[roster_fouls['player'] == 'Marreese Speights']

      season  player_id             player pos   tm  pf_per_36_min
3998    2018       3837  Marreese Speights   C  ORL            5.7
4603    2017       3837  Marreese Speights   C  LAC            6.4
5203    2016       3837  Marreese Speights   C  GSW            5.1
5815    2015       3837  Marreese Speights   C  GSW            5.6
6447    2014       3837  Marreese Speights   C  GSW            5.4
7053    2013       3837  Marreese Speights   C  MEM            5.3
7054    2013       3837  Marreese Speights   C  CLE            4.4
7604    2012       3837  Marreese Speights  PF  MEM            3.9
8194    2011       3837  Marreese Speights   C  PHI            5.9
8780    2010       3837  Marreese Speights   C  PHI            5.4
9358    2009       3837  Marreese Speights   C  PHI            5.2

Like Bogut, we see both Lee and Speights commited more fouls per 36 minutes in the season following their departures from the Warriors, with an increase of 1.9 and 1.3 fouls per 36 minutes, respectively. To be able to see if that is an oddly large number of fouls per 36 minutes, we should compare with other big men who played in the league at the time against the Warriors and were physical players, such as Tristan Thompson, Steven Adams, and Dwight Howard.

In [18]:
tt = nba[nba['player'] == 'Tristan Thompson']
tt[['season', 'player', 'tm', 'pf_per_36_min']]

      season            player   tm  pf_per_36_min
1435    2022  Tristan Thompson  TOT            3.9
1436    2022  Tristan Thompson  SAC            4.1
1437    2022  Tristan Thompson  IND            3.8
1438    2022  Tristan Thompson  CHI            3.7
2149    2021  Tristan Thompson  BOS            3.3
2799    2020  Tristan Thompson  CLE            2.6
3494    2019  Tristan Thompson  CLE            2.7
4170    2018  Tristan Thompson  CLE            3.4
4775    2017  Tristan Thompson  CLE            2.7
5366    2016  Tristan Thompson  CLE            3.2
6005    2015  Tristan Thompson  CLE            3.1
6628    2014  Tristan Thompson  CLE            2.6
7198    2013  Tristan Thompson  CLE            3.3
7752    2012  Tristan Thompson  CLE            3.4

In [19]:
sa = nba[nba['player'] == 'Steven Adams']
sa[['season', 'player', 'tm', 'pf_per_36_min']]

      season        player   tm  pf_per_36_min
600     2023  Steven Adams  MEM            3.1
1382    2022  Steven Adams  MEM            2.8
2104    2021  Steven Adams  NOP            2.5
2758    2020  Steven Adams  OKC            2.6
3445    2019  Steven Adams  OKC            2.8
4132    2018  Steven Adams  OKC            3.1
4739    2017  Steven Adams  OKC            2.9
5333    2016  Steven Adams  OKC            4.0
5964    2015  Steven Adams  OKC            4.5
6598    2014  Steven Adams  OKC            6.1

In [20]:
dh = nba[nba['player'] == 'Dwight Howard']
dh[['season', 'player', 'tm', 'pf_per_36_min']]

       season         player   tm  pf_per_36_min
908      2022  Dwight Howard  LAL            4.3
1692     2021  Dwight Howard  PHI            6.0
2378     2020  Dwight Howard  LAL            6.1
3029     2019  Dwight Howard  WAS            5.3
3731     2018  Dwight Howard  CHO            3.6
4390     2017  Dwight Howard  ATL            3.3
4970     2016  Dwight Howard  HOU            3.5
5558     2015  Dwight Howard  HOU            4.0
6214     2014  Dwight Howard  HOU            3.6
6815     2013  Dwight Howard  LAL            3.8
7386     2012  Dwight Howard  ORL            2.8
7962     2011  Dwight Howard  ORL            3.2
8574     2010  Dwight Howard  ORL            3.6
9165     2009  Dwight Howard  ORL            3.4
9740     2008  Dwight Howard  ORL            3.2
10304    2007  Dwight Howard  ORL            2.9
10836    2006  Dwight Howard  ORL            3.3
11410    2005  Dwight Howard  ORL            3.1

From the queries above, we can see that, other than Dwight Howard from 2019 onwards, most physical big men did not have more than 4.5 fouls per 36 minutes. However, in Bogut and Speights' cases, they recorded over 4.5 fouls per 36 minutes while playing for the Warriors as well. Of the remaining players from that 2015 Warriors roster, only two players really played significant roles in the teams they subsequently played for, Harrison Barnes and Justin Holiday. Let's look into their post-Warriors careers.

In [21]:
roster_fouls[roster_fouls['player'] == 'Harrison Barnes']

      season  player_id           player pos   tm  pf_per_36_min
220     2023       4089  Harrison Barnes  PF  SAC            1.4
966     2022       4089  Harrison Barnes  PF  SAC            1.3
1751    2021       4089  Harrison Barnes  PF  SAC            1.3
2425    2020       4089  Harrison Barnes  PF  SAC            1.3
3086    2019       4089  Harrison Barnes  PF  DAL            1.8
3087    2019       4089  Harrison Barnes  SF  SAC            1.6
3788    2018       4089  Harrison Barnes  PF  DAL            1.3
4428    2017       4089  Harrison Barnes  PF  DAL            1.6
5009    2016       4089  Harrison Barnes  SF  GSW            2.4
5618    2015       4089  Harrison Barnes  SF  GSW            2.3
6266    2014       4089  Harrison Barnes  SF  GSW            2.6
6867    2013       4089  Harrison Barnes  SF  GSW            2.4

In [22]:
roster_fouls[roster_fouls['player'] == 'Justin Holiday']

      season  player_id          player pos   tm  pf_per_36_min
352     2023       4102  Justin Holiday  SG  ATL            3.2
353     2023       4102  Justin Holiday  SG  DAL            3.8
1106    2022       4102  Justin Holiday  SF  IND            2.7
1107    2022       4102  Justin Holiday  SG  SAC            2.8
1861    2021       4102  Justin Holiday  SG  IND            2.2
2548    2020       4102  Justin Holiday  SF  IND            2.7
3219    2019       4102  Justin Holiday  SG  CHI            2.1
3220    2019       4102  Justin Holiday  SG  MEM            2.4
3911    2018       4102  Justin Holiday  SG  CHI            2.1
4527    2017       4102  Justin Holiday  SG  NYK            2.4
5122    2016       4102  Justin Holiday  SG  ATL            2.9
5123    2016       4102  Justin Holiday  SG  CHI            2.8
5738    2015       4102  Justin Holiday  SG  GSW            3.0
6974    2013       4102  Justin Holiday  SG  PHI            1.8

From these queries, we can see that they both had their average fouls per 36 minutes decrease after they left Golden State, which most likely means that this issue is more in the big men compared to other players.

# Conclusion
From what I have seen of this data, I do think that the big men who played on the Warriors seemed to struggle initially once they left the team, compared to most other big men who have similar styles of play. Watching the way the team plays, it does seem that there is a little more lenience allowed in terms of physicality and movement. I believe that the reason why the big men struggle with foul issues compared to the others is that the other players are less likely to be setting a lot of screens, like in the Steve Kerr led offense, while the bigger players are more likely to have to set a lot of screens and have to be more physical, leading to more fouls. The data seems to support that the referees might be more lenient but also, the play style of the Warriors could cause the bigger and more physical players to struggle outside of Golden State.

### Source
https://fadeawayworld.net/nba-media/andrew-bogut-admits-he-got-away-with-fouling-on-screens-during-his-time-with-the-golden-state-warriors-i-could-literally-clothesline-someone-off-the-next-pindown-and-not-have-it-called